version: '3'

services:
  api.laravel:
    build: .
    env_file:
      - .env.dev
    environment:
      TZ: "America/Monterrey"
      JWT_TTL: "60"
      #API_DOCUMENTOS: ""
      #RUTA_FOLDER_FTP: "//"
      IdApp: "fa82e267-3087-11ed-aed0-040300000000"
      api_base: "http://localhost:5000/api/"
      IdTiposAdquisicion: "9a142daf-004c-4153-8863-63d954ff52e9"
      APP_URL: "http://localhost:8082"
      IdEmpleado: "9a93901b-54f6-4934-946a-a09afcf11fcd"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/public
      - /var/www/html/storage
      - /var/www/html/bootstrap/cache
    ports:
      - "8082:80"
    restart: always
